name: Go Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.11", "1.12", "1.13", "1.14", "1.15"]    
    env:
      GOFLAGS: "-mod=vendor"
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Install golint
      run: go install ./vendor/golang.org/x/lint/golint
    - name: Go Lint
      run: make vet lint
    - name: Go Test
      run: make test-nohsm test-trust
